from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SCENES_DIR = SCRIPT_DIR.parent / "scenes"
GENERATED_TEXTURES_DIR = SCENES_DIR / "textures" / "generated"
OBJECTS_DIR = SCENES_DIR / "objects"

DRAGON_ASSET = OBJECTS_DIR / "xyzrgb_dragon.usda"
TEAPOT_ASSET = OBJECTS_DIR / "teapot.usda"
CORNELL_BOX_ASSET = SCENES_DIR / "cornellBox.usda"

EXISTING_TEXTURES = ["fabric.png", "wood.png", "metal.png"]

# Grid constants
GRID_ROWS = 6
GRID_COLS = 3
GRID_LAYERS = 4
OBJECT_COUNT = GRID_ROWS * GRID_COLS * GRID_LAYERS

DRAGON_FRACTION_IN_MIXED_SCENE = 0.35
DRAGON_PACKING_MARGIN = 1.05
DRAGON_OVERLAP_FACTOR = 1.0
DRAGON_Y_DROP_MULTIPLIER = 0.15

# Cornell box interior bounds
ROOM_MIN_X = -5.0
ROOM_MAX_X = 5.0
ROOM_MIN_Z = -10.0
ROOM_MAX_Z = 5.0
ROOM_MIN_Y = 0.0
ROOM_MAX_Y = 10.0

GRID_WALL_MARGIN = 0.1
OBJECT_FILL_FACTOR = 0.92

# Cornell walls
CORNELL_WALL_COLOR = (0.73, 0.73, 0.73)

# Light
CORNELL_LIGHT_EMISSIVE_STRENGTH = 20.0
